[package]
name = "wager-sol-escrow"
version = "0.1.0"
edition = "2021"

[features]
no-entrypoint = []

[dependencies]
solana-program = "1.9.4"
thiserror = "1.0.24"
arrayref = "0.3.6"

[lib]
crate-type = ["cdylib", "lib"]
